### ISSUE TITLE
Error in AnimalTracker

### ISSUE THREAD

**Issue by arispes** [mathedjoe/animaltracker#68]
R version 4.0.3
RStudio version 1.3.1093
Note: I did not get the message until I updated R and RStudio to the most recent versions.

When Trying to run animaltracker I get the following message:

The downloaded source packages are in
	‘/private/var/folders/81/ds4vfjmx605d4359_4nlnw600000gp/T/RtmpGuZGGz/downloaded_packages’
> library(animaltracker) 
> run_shiny_animaltracker()
Loading required namespace: shinyWidgets
Loading required namespace: shinycssloaders
Loading required namespace: shinythemes
Loading required namespace: sp
Loading required namespace: raster
Loading required namespace: shinyjs
Loading required namespace: V8
Loading required namespace: shinyBS
Loading required package: shiny

Listening on http://127.0.0.1:3184
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.
  74: stop
  73: errMsg
  72: shinyjs::extendShinyjs
  68: ui

**Comment by ttsukianto** [comment]
Should be fixed in the latest update to master!

**Comment by arispes** [comment]
Hi Thea, 
Unfortunately, the problem persists.  Here is what I get after running the following lines of code:
install.packages("devtools") 
library(devtools)
library(animaltracker) 
run_shiny_animaltracker()

> library(devtools)
Loading required package: usethis
> library(animaltracker) 
> run_shiny_animaltracker()
Loading required namespace: shinyWidgets
Loading required namespace: shinycssloaders
Loading required namespace: shinythemes
Loading required namespace: sp
Loading required namespace: raster
Loading required namespace: shinyjs
Loading required namespace: V8
Loading required namespace: shinyBS
Loading required package: shiny

Listening on http://127.0.0.1:3782
Warning: Error in : shinyjs: extendShinyjs: `functions` argument must be provided.
  74: stop
  73: errMsg
  72: shinyjs::extendShinyjs
  68: ui

![Screen Shot 2020-10-28 at 2 47 40 PM](https://user-images.githubusercontent.com/45365827/97495103-e23f8080-192c-11eb-8440-c88f75a3839a.png)

**Comment by mathedjoe** [comment]
Not sure if you did this separately, but you'll need to re-install
animaltracker from github. Can you try the following code and let us know
if it works?
###
devtools::install_github("mathedjoe/animaltracker")
library(animaltracker)
run_shiny_animaltracker()
 ###

**Comment by arispes** [comment]
Unfortunately, it doesn't work.  Here is what I get:

###
> library(animaltracker)
> remove.packages("animaltracker")
Removing package from ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library’
(as ‘lib’ is unspecified)
> devtools::install_github("mathedjoe/animaltracker")
Downloading GitHub repo mathedjoe/animaltracker@HEAD
Installing 1 packages: maptools
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/maptools_1.0-2.tgz'
Content type 'application/x-gzip' length 2173904 bytes (2.1 MB)
==================================================
downloaded 2.1 MB


The downloaded binary packages are in
	/var/folders/81/ds4vfjmx605d4359_4nlnw600000gp/T//RtmppgA16U/downloaded_packages
✓  checking for file ‘/private/var/folders/81/ds4vfjmx605d4359_4nlnw600000gp/T/RtmppgA16U/remotes11fca7976d73/mathedjoe-animaltracker-6c9fa1f/DESCRIPTION’ (364ms)
─  preparing ‘animaltracker’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘animaltracker_0.2.0.tar.gz’
   
* installing *source* package ‘animaltracker’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (animaltracker)
> library(animaltracker)
> run_shiny_animaltracker()
Error: lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/animaltracker/R/animaltracker.rdb' is corrupt
In addition: Warning message:
internal error -3 in R_decompress1

**Comment by arispes** [comment]
> library(animaltracker)
> run_shiny_animaltracker()
Error: cannot open file '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/animaltracker/R/animaltracker.rdb': No such file or directory
In addition: Warning message:
restarting interrupted promise evaluation

**Comment by mathedjoe** [comment]
Sergio and I talked offline. After deleting the corrupted file from the
filesystem and running  devtools::install_github("mathedjoe/animaltracker",
force=TRUE), the problem seems to be resolved.
